disabled_rules: # rule identifiers to exclude from running
  - nesting
  - trailing_whitespace
  - function_parameter_count
  - trailing_newline
  - colon
  - opening_brace
  - superfluous_disable_command
  - force_try
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting
    
force_try:
  severity: warning # explicitly. Give warning only for force try

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
    - x
    - y
    - i
    - j

vertical_whitespace:
  max_empty_lines: 5

line_length:
  warning: 220
  error: 300

type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 55
    error: 60
  excluded: iPhone # excluded via string
reporter: "xcode"
